#!/usr/bin/env bash
#
# Script name: dm-icons
# Description: copy emoji to clipboard
# Dependencies: dmenu, python3, awk, xclip, notify-send
# GitLab: 


# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.

set -euo pipefail
_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper.sh" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper.sh"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main() {
glyphlist='/usr/lib/glyphlist'
font_family='"FantasqueSansMono Nerd Font Mono"'
font_size="25"
# Get user selection via dmenu from emoji file.
if [ -e $glyphlist ]
then
    chosen=$(cut -d ';' -f1 $glyphlist | dmenu -l 15 -fn "$font_family-$font_size" | sed "s/ .*//")
else
    echo -en "$(sudo curl https://www.nerdfonts.com/cheat-sheet \
        | grep 'class="class-name">' \
        | sed 's/ *<div class="class-name">//; s/<\/div><div class="codepoint">/ \\u/; s/<\/div>//; s/\(.* \)\(.*\)/\2 \1/' \
        )" > $glyphlist
    chosen=$(cut -d ';' -f1 $glyphlist | dmenu -l 30 | sed "s/ .*//")
fi

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
if [ -n "${1-}" ]; then
	xdotool type "$chosen"
else
	printf "$chosen" | xclip -selection clipboard
	notify-send "'$chosen' copied to clipboard." &
fi
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
